# Generated by Django 5.0.3 on 2024-07-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_alter_cart_food_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_type", models.CharField(max_length=255)),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Tax percentage(%)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Tax",
            },
        ),
    ]
