# Generated by Django 5.0.3 on 2024-07-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_address_line_1_userprofile_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="country",
        ),
    ]
