# Generated by Django 5.0.3 on 2024-07-21 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_footitem_category"),
        ("vendor", "0011_alter_vendor_vendor_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendor",
            ),
        ),
    ]
