# Generated by Django 5.0.3 on 2024-06-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tax_data",
        ),
    ]
