# Generated by Django 5.0.3 on 2024-07-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_total_data_order_vendors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="country",
        ),
    ]
